<a href="https://colab.research.google.com/github/kondasreenu/Python_Numpy/blob/main/P_Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Introduction to Numpy**

https://numpy.org/


Key Reasons:

1. Numpy is written in C

2. More efficient with memory usage

3. can run sub-task in parallel

4. Linear algebra and Mathematics

5. Image Processing



#Numpy fundamentals

First Step is import

import numpy as np



In [30]:
import numpy as np

my_1d_array = np.array([1,2,3])

type(my_1d_array)

my_1d_array.shape


#Accessing elements

print(my_1d_array[0])

print(my_1d_array[0:3]) #Slicing


print(my_1d_array[-1]) #Slicing



#multi dimensional array

my_2d_array = np.array([[1,2,3],[4,5,6]])
print(my_2d_array.shape) #2 rows and 3 columns


print(my_2d_array[0]) #0th row


print(my_2d_array[0][2]) #0th row, 2nd element

print(my_2d_array) 

print(my_2d_array[0:1,0:2]) #


np.zeros(3) #1D array with 3 zeros

np.zeros((3,3)) #2D array with 3 * 3 zeros

np.zeros((3,3,3)) #3D array with 3 * 3 * 3 zeros, Cube Shape

np.ones((3,3,3)) #3D array with 3 * 3 * 3 zeros, Cube Shape



np.full((3,3),5)

np.arange(10)

np.arange(2,10)


np.arange(2,10,2)


np.linspace(1,5,10)

float_array = np.linspace(1,5,10)

np.round(float_array,2)

np.random.rand(5)

np.random.rand(5,2)






1
[1 2 3]
3
(2, 3)
[1 2 3]
3
[[1 2 3]
 [4 5 6]]
[[1 2]]


array([[0.06444878, 0.21390182],
       [0.11732586, 0.43365054],
       [0.31034792, 0.93429106],
       [0.26655112, 0.4099309 ],
       [0.94015323, 0.87490974]])

Numpy Array Operations


1D Array, 2D Arrays


Aggregate functions


How to find maximum value in each row
my_2d_arrray.max()

my_2d_arrray.max(axis=0)

my_2d_arrray.max(axis=1)

my_2d_arrray.argmax(axis=0)





sort()

airthmetic operatiotns


Adding constants

Adding two arrays



square()

sqrt()


sign()

sin()
cos()
tan()


np.dot(a,b)  dot product



updating array elements


np.where() where function




np.argwhere()



np.all()


np.any()





np.vstack()


np.hstack()


flatten()



